// flow-typed signature: fc1dd8dedbfe8d8854e16586f725b8ec
// flow-typed version: <<STUB>>/gatsby-link_v^1.6.28/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-link'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-link' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gatsby-link/index' {
  declare module.exports: $Exports<'gatsby-link'>;
}
declare module 'gatsby-link/index.js' {
  declare module.exports: $Exports<'gatsby-link'>;
}
